# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Meedan Code
email: code@meedan.com
description: > # this means to ignore newlines until "baseurl:"
  Make sense of the global web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://code.meedan.com" # the base hostname & protocol for your site
twitter_username: meedan
github_username:  meedan

# Build settings
markdown: kramdown
highlighter: rouge
# Markdown-specific settings
kramdown:
  auto_ids: true # Auto-generate ID's for headings

# extra gems
# https://github.com/jekyll/jekyll-seo-tag
gems:
  - jekyll-seo-tag
  - rouge

# exclude the ./vendor directory
exclude:
  - vendor

# config elements specific to jeckyll-seo-tag
# https://github.com/jekyll/jekyll-seo-tag
twitter:
  username: meedan
logo: https://meedan.com/images/logos/meedan-logo-horizontal-3@2x.png

defaults:
  - values:
      image: https://meedan.com/images/logos/meedan-logo-horizontal-3@2x.png
